name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            python-version: '3.12'
            experimental: false
          # - os: ubuntu-20.04
          #   python-version: '3.13'
          #   experimental: true
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install system packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y bison cmake flex g++

    - name: Setup Developer Command Prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Dependencies
      run: pip install -r requirements.txt

    # We have to put continue-on-error at the step level rather than the job
    # level because the UI is broken:
    # https://github.com/github-community/community/discussions/15452.

    - name: Run Tests
      env:
        LINT: ${{ runner.os == 'Linux' && matrix.python-version == '3.12' }}
      run: python build_scripts/ci_script.py
      continue-on-error: ${{ matrix.experimental }}

    - uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}

