name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.11', '3.12']
        shard: [shard_1, shard_2, shard_3, shard_4]  # Keep this synced with ALL_TESTS_SHARD_COUNT
        exclude:
          - os: macos-latest
            python-version: '3.11'
          - os: windows-latest
            python-version: '3.11'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install system packages
      if: runner.os == 'Linux'
      run: sudo apt-get install -y bison cmake flex g++

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Build
      run: python build_scripts/build.py

    - name: Run Tests
      run: python build_scripts/run_tests.py -f -v test_all_${{ matrix.shard }}_of_4  # Keep this synced with ALL_TESTS_SHARD_COUNT
      continue-on-error: ${{ matrix.python-version == '3.13' }}

  check:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install system packages
      if: runner.os == 'Linux'
      run: sudo apt-get install -y bison cmake flex g++

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Lint
      if: runner.os == 'Linux' && matrix.python-version == '3.12'
      run: pylint build_scripts pytype pytype_extensions setup.py

    - name: Build
      run: python build_scripts/build.py

    - name: Type Check
      run: python out/bin/pytype -j auto
